default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  username:
  password:
  timeout: 5000

development:
  <<: *default
  database: jarvis_development

test:
  <<: *default
  database: jarvis_test

production:
  <<: *default
  database: jarvis_production
